apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData: # Do not require to put the values in base64
  # You can include additional key value pairs as you do with Opaque Secrets
  username: admin
  password: "12345678"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    env:
      - name: USERTEST
        valueFrom:
            secretKeyRef:
              name: secret1
              key: username
      - name: PASSWORDTEST
        valueFrom:
            secretKeyRef:
              name: secret1
              key: password
    volumeMounts:
    - name: test
      mountPath: "/opt" # Where to mount the secret in the container
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: secret1
      items:
      - key: username
        path: user.txt # Will create a file in /opt/user.txt with the value specified in the Secret for the key username
