apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  username: aG9sYQ== # Must be in base64
  password: Y2hhdQ== # Must be in base64