apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
type: Opaque
stringData: # Do not require to put the values in base64
  # You can include additional key value pairs as you do with Opaque Secrets
  username: hola
  password: chau
