apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
    labels:
        app: front
data:
    test: hola
    nginx: |
        server {
            listen       80;
            server_name  localhost;    
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }    
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: front
spec: # ReplicaSet stuff
  replicas: 1
  selector:
    matchLabels:
      app: front
  template: # Pod stuff
    metadata:
      labels:
        app: front
    spec:
        containers:
            - name: nginx
              image: nginx:alpine
              volumeMounts: # Volumes to mount on the Pod
              - name: nginx-vol # Volume name
                mountPath: /etc/nginx/conf.d # Path where to place the volume on the container
        volumes:
            - name: nginx-vol # Volume name
              configMap:
                # Provide the name of the ConfigMap containing the files you want
                # to add to the container
                name: nginx-config # Name of the ConfigMap
                items: # Keys inside the ConfigMap. If not defined mount every key that it finds on the ConfigMap
                    # - key: nginx # Key of the ConfigMap key to mount
                    #   path: default.conf # Name that will have once mounted on the Pod
                  