apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: front
spec: # ReplicaSet stuff
  replicas: 3
  selector:
    matchLabels:
      app: front
  template: # Pod stuff
    metadata:
      labels:
        app: front
    spec: # Container/s
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
    name: my-service
    labels:
        app: front
spec:
    type: ClusterIP # Define a Service o type ClusterIP
    selector:
        app: front # Label to observe pods
    ports:
        - protocol: TCP
          port: 8080 # Port where the Service listens
          targetPort: 80 # Port inside the container to route to