apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Changes port to 8080"
  name: deployment-test
  labels:
    app: front
spec: # ReplicaSet stuff
  revisionHistoryLimit: 10 # Set how many rollout histories to keep of this Deployment
  replicas: 3
  selector:
    matchLabels:
      app: front
  template: # Pod stuff
    metadata:
      labels:
        app: front
    spec: # Container/s
      containers:
      - name: nginx
        image: nginx:test-fake
        ports:
            - containerPort: 100
