apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "100" # How much CPUs maximum, not guaranteed by k8s
      requests:
        cpu: "100" # How much CPUs to be guaranteed by k8s. It will stay on Pending state
    args:
    - -cpus
    - "2"