apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi" # How much memory maximum, not guaranteed by k8s
      requests:
        memory: "100Mi" # How much memory to be guaranteed by k8s
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"] # Ask more memory than the limit. Throws: OOMKilled