apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1" # How much CPUs maximum, not guaranteed by k8s
      requests:
        cpu: "0.5" # How much CPUs to be guaranteed by k8s. == 500m (milicores)
    args:
    - -cpus
    - "2" # If it excedes the amount of CPUs, it doesn't crash, but it stays with the maximum, in this case 1 CPU
