---
apiVersion: v1
kind: Namespace
metadata:
    name: prod
    labels:
        name: prod
---
# The limitRange only operates on the namespace that has been created
apiVersion: v1
kind: LimitRange
metadata:
    name: min-max
    namespace: prod
spec:
    limits:
    - max:
        memory: 1Gi
        cpu: 1
      min:
        memory: 100M
        cpu: 100m
      type: Container
---
apiVersion: v1 # Api version
kind: Pod
metadata:
    name: podtest3
    namespace: prod
    labels:
        app: backend
        env: prod
spec:
    containers:
    - image: nginx:alpine
      name: cont1
      resources:
        limits:
            memory: 2G # Should throw: Error from server (Forbidden)
            cpu: 2
        requests:
            memory: 400M
            cpu: 0.3