apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on
  labels:
    app: backend
spec: # ReplicaSet stuff
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template: # Pod stuff
    metadata:
      labels:
        app: backend
    spec: # Container/s
      containers:
      - name: backend
        image: k8s-hands-on:v2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
    name: backend-k8s-hands-on
    labels:
        app: backend
spec:
    type: NodePort # Define a Service of type NodePort
    selector:
        app: backend # Label to observe pods
    ports:
        - protocol: TCP
          port: 80 # Port where the Service listens
          targetPort: 9090 # Port inside the container to route to