apiVersion: v1 # Api version
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
  - image: nginx:alpine
    name: cont1
---
apiVersion: v1 # Api version
kind: Pod
metadata:
  name: podtest3
spec:
  containers:
  - image: nginx:alpine
    name: cont1